dataset:
  name: &name dob_jobapplications
  version: "{{ version }}"
  acl: public-read
  source:
    socrata:
      uid: ic3t-wcy2
      format: csv
    options:
      - "AUTODETECT_TYPE=NO"
      - "EMPTY_STRING_AS_NULL=YES"
    geometry:
      SRS: null
      type: NONE

  destination:
    name: *name
    geometry:
      SRS: null
      type: NONE
    options:
      - "OVERWRITE=YES"
      - "PRECISION=NO"
    fields: 
      - jobnumber
      - jobdocnumber
      - borough
      - housenumber
      - streetname
      - block
      - lot
      - bin
      - jobtype
      - jobstatus
      - jobstatusdesc
      - latestactiondate
      - buildingtype
      - communityboard
      - cluster
      - landmarked
      - adultestab
      - loftboard
      - cityowned
      - littlee
      - pcfiled
      - efilingfiled
      - plumbing
      - mechanical
      - boiler
      - fuelburning
      - fuelstorage
      - standpipe
      - sprinkler
      - firealarm
      - equipment
      - firesuppression
      - curbcut
      - other
      - otherdesc
      - applicantfirstname
      - applicantlastname
      - applicantprofessionaltitle
      - applicantlicensenumber
      - professionalcert
      - prefilingdate
      - paid
      - fullypaid
      - assigned
      - approved
      - fullypermitted
      - initialcost
      - totalestfee
      - feestatus
      - existingzoningsqft
      - proposedzoningsqft
      - horizontalenlrgmt
      - verticalenlrgmt
      - enlargementsqfootage
      - streetfrontage
      - existingnumstories
      - proposednumstories
      - existingheight
      - proposedheight
      - existingdwellingunits
      - proposeddwellingunits
      - existingoccupancy
      - proposedoccupancy
      - sitefill
      - zoningdist1
      - zoningdist2
      - zoningdist3
      - specialdistrict1
      - specialdistrict2
      - ownertype
      - nonprofit
      - ownerfirstname
      - ownerlastname
      - ownerbusinessname
      - ownerhousenumber
      - ownerhousestreetname
      - city
      - state
      - zip
      - ownerphone
      - jobdescription
      - dobrundate
      - jobs1no
      - totalconstructionfloorarea
      - withdrawalflag
      - signoffdate
      - specialactionstatus
      - specialactiondate
      - buildingclass
      - jobnogoodcount
      - latitude
      - longitude
      - councildistrict
      - censustract
      - nta
      - gisbin
    sql: null

  info:
    description: |
      # The Department of Buildings (DOB) issues permits
      This dataset contains all job applications submitted through the Borough Offices, 
      through eFiling, or through the HUB, which have a "Latest Action Date" since January 1, 2000. 
      This dataset does not include jobs submitted through DOB NOW. 
      See the DOB NOW: Build – Job Application Filings dataset for DOB NOW jobs.
    url: https://data.cityofnewyork.us/Housing-Development/DOB-Job-Application-Filings/ic3t-wcy2
    dependents: []