name: Check Corrections - housing_input_research.csv
on:
  pull_request:
    paths:
      - 'developments_build/data/housing_input_research.csv'
    types: [opened]

jobs:
  Test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.4
      
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: install pandas
        run: python -m pip install pandas
      
      - name: Check Fields Order
        working-directory: developments_build/data
        shell: python 
        run: |
          import pandas as pd
          
          df = pd.read_csv('housing_input_research.csv', dtype=str)
          correct_columns = ["job_number", "field", "old_value", "new_value", "reason", "edited_date", "editor"]
          current_columns = list(df.columns)
          assert current_columns == correct_columns, "Incorrect column order {0}".format('|'.join(current_columns))
      
      - name: Check Possible Fields
        working-directory: developments_build/data
        shell: python 
        run: |
          import pandas as pd
          
          df = pd.read_csv('housing_input_research.csv', dtype=str)
          possible_columns = [
            'classa_init', 'classa_prop', 'date_permittd', 
            'hotel_init', 'hotel_prop', 'job_inactive', 
            'latitude', 'longitude', 'otherb_init', 
            'otherb_prop', 'remove', 'stories_prop'
          ]
          current_columns = list(df.field.unique())
          for col in current_columns:
            assert col in possible_columns, "This field name {0} is not supported for correction".format(col)
