name: CI
on: [push]
jobs:
  skip:
    name: Build and test
    runs-on: self-hosted
    if: "contains(github.event.head_commit.message, '[large]')"
    steps:
      - run: echo "${{ github.event.head_commit.message }}"
  _01_dataloading:
    name: load large DOB tables ...
    needs: skip
    container:
      image: sptkl/cook:latest
    runs-on: self-hosted
    env:
      RECIPE_ENGINE: ${{ secrets.RECIPE_ENGINE }}
      BUILD_ENGINE: ${{ secrets.BUILD_ENGINE }}
      EDM_DATA: ${{ secrets.EDM_DATA }}
    steps:
      - uses: actions/checkout@v2
      - name: dataloading ..
        working-directory: developments_build
        shell: bash
        run: |
          python3 python/large_dataloading.py