name: CI
on: [push]
jobs:
  skip:
    name: Build and test
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '[large]')"
    steps:
      - run: echo "${{ github.event.head_commit.message }}"
  load_large_tables:
    name: load large DOB tables ...
    needs: skip
    runs-on: ubuntu-latest
    env:
      RECIPE_ENGINE: ${{ secrets.RECIPE_ENGINE }}
      BUILD_ENGINE: ${{ secrets.BUILD_ENGINE }}
      EDM_DATA: ${{ secrets.EDM_DATA }}
    steps:
      - uses: actions/checkout@v2
      - name: dataloading ..
        working-directory: developments_build
        run: |
          docker run --rm\
            -v $(pwd):/developments_build\
            -w /developments_build\
            -e EDM_DATA=$EDM_DATA\
            -e RECIPE_ENGINE=$RECIPE_ENGINE\
            -e BUILD_ENGINE=$BUILD_ENGINE\
            sptkl/cook:latest bash -c "
                python3 python/large_dataloading.py"