name: Publish
on:
  release:
    types:
      - published
  workflow_dispatch:
  

jobs:
  publish:
    name: Publishing ...
    runs-on: ubuntu-20.04
    env:
      AWS_S3_ENDPOINT: ${{ secrets.DO_S3_ENDPOINT }}
      AWS_ACCESS_KEY_ID: ${{ secrets.DO_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.DO_SECRET_ACCESS_KEY }}
      AWS_S3_BUCKET: edm-recipes
    steps:
      - uses: actions/checkout@v2

      - name: Get Version
        id: version
        run: |
          source developments_build/version.env
          echo "::set-output name=version::$VERSION"
          echo "Version is $VERSION"
      
      - uses: NYCPlanning/action-library-archive@v1.1
        id: dcp_housing
        with:
          path: templates/dcp_housing.yml 
          s3: true
          latest: true
          compress: true
          output_format: shapefile csv pgdump
          version: ${{ steps.version.outputs.version }}
      
      - uses: NYCPlanning/action-library-archive@v1.1
        id: dcp_developments
        with:
          path: templates/dcp_developments.yml 
          s3: true
          latest: true
          compress: true
          output_format: shapefile csv pgdump
          version: ${{ steps.version.outputs.version }}
      
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID_DATA_ENGINEERING }}
          service_account_key: ${{ secrets.GCP_GCS_BQ_SA_KEY }}
          export_default_credentials: true
      
      - name: Archive to BigQuery
        run: |
          curl -O https://nyc3.digitaloceanspaces.com/edm-recipes/datasets/dcp_developments/$VERSION/dcp_developments.csv
          location=US
          dataset=dcp_developments
          tablename=$dataset.$VERSION
          bq show $dataset || bq mk --location=$location --dataset $dataset
          bq show $dataset || bq mk $tablename
          bq load \
              --location=$location\
              --source_format=CSV\
              --quote '"' \
              --skip_leading_rows 1\
              --replace\
              --allow_quoted_newlines\
              $tablename dcp_developments.csv schemas/dcp_developments.json